// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqFARUI59FHngFrcSI6AUFpaWZJT99fMU',
    appId: '1:543966365178:web:9ff75692b5e9e451c61043',
    messagingSenderId: '543966365178',
    projectId: 'halldinning-ebbf3',
    authDomain: 'halldinning-ebbf3.firebaseapp.com',
    storageBucket: 'halldinning-ebbf3.firebasestorage.app',
    measurementId: 'G-SEQTS3QGJV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClLzo7yCRMF8N-soKEZQmL4_MTHTKmBPM',
    appId: '1:543966365178:android:5c990d619351b4c0c61043',
    messagingSenderId: '543966365178',
    projectId: 'halldinning-ebbf3',
    storageBucket: 'halldinning-ebbf3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoDQpoMrZLyFuHqC1RrPsvCj3OwlxsmN4',
    appId: '1:543966365178:ios:8a8dc22a782b8871c61043',
    messagingSenderId: '543966365178',
    projectId: 'halldinning-ebbf3',
    storageBucket: 'halldinning-ebbf3.firebasestorage.app',
    iosClientId: '543966365178-s6704da40ljr9lo8kr3fn00hmf2497us.apps.googleusercontent.com',
    iosBundleId: 'com.example.halldinningapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoDQpoMrZLyFuHqC1RrPsvCj3OwlxsmN4',
    appId: '1:543966365178:ios:8a8dc22a782b8871c61043',
    messagingSenderId: '543966365178',
    projectId: 'halldinning-ebbf3',
    storageBucket: 'halldinning-ebbf3.firebasestorage.app',
    iosClientId: '543966365178-s6704da40ljr9lo8kr3fn00hmf2497us.apps.googleusercontent.com',
    iosBundleId: 'com.example.halldinningapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqFARUI59FHngFrcSI6AUFpaWZJT99fMU',
    appId: '1:543966365178:web:90e5d73bdf862ad4c61043',
    messagingSenderId: '543966365178',
    projectId: 'halldinning-ebbf3',
    authDomain: 'halldinning-ebbf3.firebaseapp.com',
    storageBucket: 'halldinning-ebbf3.firebasestorage.app',
    measurementId: 'G-RQJSN65Y9Y',
  );
}
