// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAn0Ico5kuOK3suJKGeLc0yeNHu_9TJkzo',
    appId: '1:634566928443:web:f74d8219d4421e1104541e',
    messagingSenderId: '634566928443',
    projectId: 'diningmanagement-547f3',
    authDomain: 'diningmanagement-547f3.firebaseapp.com',
    storageBucket: 'diningmanagement-547f3.firebasestorage.app',
    measurementId: 'G-1V7VX6CC5H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0npyogrlv_QNdPoYX_bhpKQaBrz2nCWM',
    appId: '1:634566928443:android:50d7a5265e709da804541e',
    messagingSenderId: '634566928443',
    projectId: 'diningmanagement-547f3',
    storageBucket: 'diningmanagement-547f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDumDyAZb6UU1cUpg6unSgcxHShYU0FHKY',
    appId: '1:634566928443:ios:4775cc504178d52104541e',
    messagingSenderId: '634566928443',
    projectId: 'diningmanagement-547f3',
    storageBucket: 'diningmanagement-547f3.firebasestorage.app',
    iosClientId: '634566928443-5caaig635kvvsat195nracck9euqc6su.apps.googleusercontent.com',
    iosBundleId: 'com.example.hallDiningManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDumDyAZb6UU1cUpg6unSgcxHShYU0FHKY',
    appId: '1:634566928443:ios:4775cc504178d52104541e',
    messagingSenderId: '634566928443',
    projectId: 'diningmanagement-547f3',
    storageBucket: 'diningmanagement-547f3.firebasestorage.app',
    iosClientId: '634566928443-5caaig635kvvsat195nracck9euqc6su.apps.googleusercontent.com',
    iosBundleId: 'com.example.hallDiningManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAn0Ico5kuOK3suJKGeLc0yeNHu_9TJkzo',
    appId: '1:634566928443:web:29096e8256efa51c04541e',
    messagingSenderId: '634566928443',
    projectId: 'diningmanagement-547f3',
    authDomain: 'diningmanagement-547f3.firebaseapp.com',
    storageBucket: 'diningmanagement-547f3.firebasestorage.app',
    measurementId: 'G-CVH4P7W59J',
  );

}